name: Rinon Ninqueon
title: Rinon Ninqueon Electronics
email: mail@rinonninqueon.com
description: "Заметки и статьи по электронике и музыке."
baseurl: ""
url: "http://rinonninqueon.com"

destination: ./_site
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "smart"]
relative_permalinks: true
permalink: /:categories/:title/
pagination: 15
paginate_path : "/page:num"
highlighter: false
encoding: utf-8